apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.17.137.187
    path: /nfs_file/sysbench_log_dir
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sysbench-job
spec:
  template:
    spec:
      containers:
        - name: sysbench-container
          image: 172.17.136.180/wang/sysbench-alpine:v2.0
          volumeMounts:
            - name: nfs-volume
              mountPath: /sysbench_log_dir
          env:
            - name: mysql_host
              value: 172.17.139.180
            - name: mysql_user
              value: "admin"
            - name: mysql_password
              value: "!QAZ2wsx"
            - name: mysql_port
              value: "3307"
            - name: test_time
              value: "60"
            # - name: report_interval
            #   value: "3"
            # - name: threads
            #   value: "12"
            # - name: tables
            #   value: "12"
            # - name: table_size
            #   value: "500000"
          command:
            - "sh"
            - "/sysbench/sysbench.sh"
            - "8"
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
      restartPolicy: Never
  backoffLimit: 4

