name: Docker Multi-Arch Build & Test

on:
  workflow_dispatch: {}  # 手动触发

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build multi-arch Docker image and test

    steps:
      # 拉取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Docker Buildx（用于构建多平台镜像）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 创建 Buildx 构建器实例
      - name: Create new builder instance
        run: docker buildx create --name multiarch-builder --use

      # 构建 amd64 镜像，并导出为本地 tar 文件（注意 --output type=docker 只能用于单平台）
      - name: Build amd64 image and export to tar
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output type=docker,dest=sysbench-amd64.tar \
            -t sysbench:test .

      # 将 tar 包上传为 GitHub Artifact，供后续下载或调试使用
      - name: Upload Docker image tarball
        uses: actions/upload-artifact@v4
        with:
          name: sysbench-image-amd64
          path: sysbench-amd64.tar

      # 导入镜像到本地 Docker（仅在当前 Runner 用于测试）
      - name: Load Docker image
        run: docker load -i sysbench-amd64.tar

      # 运行测试：验证镜像是否能正常运行脚本（例如 sysbench.sh --help）
      - name: Test Docker image
        run: |
          docker run --rm sysbench:test sh /sysbench/sysbench.sh --help
