name: Docker Multi-Arch Build & Test

on:
  workflow_dispatch: {}  # 支持手动触发（你可以从 GitHub UI 点击运行）

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build multi-arch Docker image and test

    steps:
      # 拉取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Docker Buildx（支持多架构构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 创建 Buildx 构建器
      - name: Create builder instance
        run: docker buildx create --name multiarch-builder --use

      # 构建 amd64 镜像，并导出为本地 tar 包（只构建，不推送）
      - name: Build amd64 image and export to tar
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file sysbench-3.0.dockerfile \
            --output type=docker,dest=sysbench-amd64.tar \
            -t sysbench:test .

      # 上传镜像 tar 文件为 artifact，供你手动下载
      - name: Upload Docker image tarball
        uses: actions/upload-artifact@v4
        with:
          name: sysbench-image-amd64
          path: sysbench-amd64.tar

      # 将镜像 tar 文件加载到当前 runner 中
      - name: Load Docker image
        run: docker load -i sysbench-amd64.tar

      # 测试镜像是否能正常运行 sysbench --help
      - name: Test Docker image
        run: |
          docker run --rm sysbench:test sysbench --help
